### ISSUE TITLE
UUD Unraid Forum link dead

### ISSUE THREAD

**Issue by dschaper** [HStep20/Ultimate-Unraid-Dashboard-Guid#2]
https://forums.unraid.net/topic/96895-ultimate-unraid-dashboard-uud/ seems to be a dead link now.

**Comment by HStep20** [comment]
Yep. The original forum post seems to have been deleted for some reason. Ill be adding the Grafana Dashboard Config itself to the repo asap

**Comment by HStep20** [comment]
The latest commit has the GUS-Dashboard.json which you need to set up Grafana. If you were in the middle of setting it up, can you go ahead and test the import of it into Grafana? All personal info should be scrubbed, but I had to do it in the json file itself as the dashboard options were being finicky
