### ISSUE TITLE
Telegraf.conf mount issue

### ISSUE THREAD

**Issue by necromancyr** [HStep20/Ultimate-Unraid-Dashboard-Guid#3]
I keep getting the following error...tried just mounting the directory, but then telegraf crashes out saying the telegraf.conf doesn't exist.  Not sure what to do next - event tried recreating everything.  

_Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/mnt/user/appdata/monitorstack/GUS-telegraf/telegraf.conf" to rootfs at "/etc/telegraf/telegraf.conf": mount /mnt/user/appdata/monitorstack/GUS-telegraf/telegraf.conf:/etc/telegraf/telegraf.conf (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type_

**Comment by necromancyr** [comment]
Ok, so after testing this 20 different ways I found the issue was a typo in my config folder setup which resulted in the directory created and not mounting issue vs. something broader.  So check that if you have this come up.

**Comment by HStep20** [comment]
Thanks for the update! Hopefully it helps someone in the future
