### ISSUE TITLE
Docker Icons: Special Configuration Required?

### ISSUE THREAD

**Issue by necromancyr** [HStep20/Ultimate-Unraid-Dashboard-Guid#4]
Is a special configuration required to have icons show for docker containers?  Queries look right and the unraidapi is responding - but I'm only seeing text names and no icons w/in Grafana despite icons being set in Unraid.

**Comment by HStep20** [comment]
Are you using Firefox? Ive had some funkery with it where you need to authenticate/log in to unraid via grafana in order to get icons to show. 

Right click on one of the icon sections/names, and 'open in new tab'. It should link you to the Unraid login page. Once you log in, refresh grafana, and it _should_ show the icons

**Comment by necromancyr** [comment]
No actual link off the icons/section names interestingly (in Grafana) - there is an image there, but if I try to view it, it's an IP that's off -  _http://10.0.0.101/state/plugins/dynamix.docker.manager/images/nzbhydra2-icon-9b16025e8044f95b2aa90e1f9469c7f33b62e76c.png_

Not sure where it's getting the 10.0.0.101 from at all.

**Comment by HStep20** [comment]
Interesting. Thats the internal IP of my server. It looks like something in the grafana dashboard is still using that, even though I tried to scrub it as much as possible when uploading it after the forum was removed. 

Ill look into it more later, but it may give you a starting point to find out as well. Some IP may be configured incorrectly

**Comment by necromancyr** [comment]
That did it - in the config for that panel, right hand side, changing the base URL to my Unraid IP fixed it.  Still no click through, but not certain if it should have that or not?

**Comment by HStep20** [comment]
If you mean Click Through, you mean clicking on an Icon opens the web app, then no. However, if you still are not seeing icons on the docker list, and just seeing a bunch of names, you should be able to now right click and open in a new tab to auth through unraid, so Grafana can 'see' the icons

![image](https://user-images.githubusercontent.com/6693120/208784683-019342e4-1f2d-4d6c-8563-69e5c7d9c3e9.png)

(assuming I understand that this section is what you are referring to)

**Comment by necromancyr** [comment]
Yup - can see the icons there.  Perfect, working.  Found another minor issue - the "servername" block has a hardcoded IP as well vs. server details.  Going through and aligning other parts - will post anything else I find.

**Comment by necromancyr** [comment]
Looks like a large portion of UnraidAPI doesn't work in 6.11 any longer, which definitely causes major failures across Unraid specific aspects (array status, VMs, etc.).

**Comment by necromancyr** [comment]
So, I'll close this as resolved given the solutions noted above.  Do suggest anyone finding this go through the dashboard for anything that looks off to check how it's referenced, if your hardware actually supports it (e.g., mine won't report fan info or certain temps), etc.  

Also, auto-population of certain items (drive names) from the selectors at the top may not work correctly in all cases - certain drives are referred to differently between HDDTemp data and other data, so that may need to be fixed manually as well.
