### ISSUE TITLE
Broken Link - ultimate-unraid-dashboard-uud

### ISSUE THREAD

**Issue by Sn3akyP3t3** [HStep20/Ultimate-Unraid-Dashboard-Guid#5]
I'm trying to find information about this.  Found a broken link that may be the wealth of information I needed to know.  Not sure what the replacement link would be otherwise it would suggest it.  This is the broken link: https://forums.unraid.net/topic/96895-ultimate-unraid-dashboard-uud/

**Comment by HStep20** [comment]
Yes, as noted in my latest commit, the forum page was taken down for an unknown reason. However, if you look at the bottom of the ReadMe, you'll see Ive included a link to the Internet Archives 'Wayback Machine' archived version of the page. It includes all of the information you may need - though, unfortunately, doesn't have working links to downloadable files
